import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.scss'
import AppProvider from '@/providers/AppProvider'
import icon from './favicon.ico'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Zed-messenger',
	description: 'Generated by create next app',
	manifest: '/manifest.json',
	icons: icon.src,
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<AppProvider>{children}</AppProvider>
			</body>
		</html>
	)
}
